image: alpine:latest

before_script:
  - apk add --no-cache git

mirror_to_github:
  script:
    - git config --global user.name "${GITHUB_USERNAME}"
    - git config --global user.email "${GITHUB_EMAIL}"
    - git clone --mirror "${CI_REPOSITORY_URL}" repo
    - cd repo
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/trading-scheduler.git
    - git push --mirror github
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always